export const ARCADE_TITLE_OPTIONS = [
  "maimai DX",
  "maimai",
  "CHUNITHM",
  "音击",
  "SOUND VOLTEX",
  "beatmania IIDX",
  "jubeat",
  "jubeat音乐魔方",
  "Pop'n music",
  "GD DrumMania",
  "GD GuitarFreaks",
  "Reflec beat",
  "GROOVE COASTER",
  "DANCERUSH",
  "DANZBASE",
  "DanceEvolution",
  "DJMAX Technika",
  "Project DIVA Arcade",
  "WACCA",
  "PUMP IT UP",
  "太鼓之达人",
  "太鼓达人(旧代)",
  "湾岸MIDNIGHT",
  "头文字D",
  "宝可梦加傲乐",
  "宝可梦明耀之星",
  "星光",
  "炸弹少女",
  "舞立方EVO",
  "鼓王"
] as const;
